version: "3"

services:

  webserver:
    build: 
      context: ./app/${PHPVERSION}
    container_name: '${COMPOSE_PROJECT_NAME}-${PHPVERSION}'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    volumes: 
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/var/log/apache2
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}



