version: '3.4'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  prometheus-exporter:
    image: prom/node-exporter
    container_name: service
    hostname: service
    ports:
      - ${PROMETHEUS_EXPORTER_PORT}:9100
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:  
      - ./grafana.ini:/etc/grafana/grafana.ini

