version: "3"
services:
  seata-server:
    image: seataio/seata-server:${SEATA_VERSION}
    hostname: seata-server
    ports:
      - "${SEATA_PORT}:8091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file