version: '3'
services:
    xxljob01:
        image: docker.io/xuxueli/xxl-job-admin:2.1.2
        container_name: xxljob01
        ports:
            - "8090:8080"
            - "8099:9999"
        environment:
            PARAMS: '--spring.datasource.url=jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=${DB_USER}  --spring.datasource.password=${DB_PASSWORD}'
