version: '3'
services:
  xxljob:
    image: docker.io/xuxueli/xxl-job-admin:2.1.2
    container_name: '${PROJECT_NAME}-xxljob'
    ports:
      - "${XXL_JOB_ADMIN_PORT}:8080"
      - "${XXL_JOB_REGISTER_PORT}:9999"
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://${XXL_JOB_DB_HOST}:${XXL_JOB_DB_PORT}/${XXL_JOB_DB_NAME}?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=${XXL_JOB_DB_USER}  --spring.datasource.password=${XXL_JOB_DB_PASSWORD}'
    networks:
      - xxljob
networks:
  xxljob:
    driver: bridge