version: "3"
services:
  redis:
    container_name: '${PROJECT_NAME}-redis'
    image: redis:latest
    volumes:
      - ./redis/data:/data
    command:
      redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - redis

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    container_name: '${PROJECT_NAME}-phpredisadmin'
    environment:
      REDIS_1_HOST: ${REDIS_1_HOST}
      REDIS_1_NAME: MyRedis
      REDIS_1_AUTH: ${REDIS_PASSWORD}
      ADMIN_USER: ${REDIS_ADMIN_USER}
      ADMIN_PASS: ${REDIS_ADMIN_PASS}
    ports:
      - '${REDIS_ADMIN_PORT}:80'
    networks:
      - redis

networks:
  redis:
    driver: bridge